-- Ensure every officer referenced by the import has a ta_profiles row.
-- Safe: on conflict do nothing (never overwrites an existing profile).
-- Run this BEFORE the import parts if the diagnostic shows missing profiles.
begin;
insert into ta_profiles(email,name,designation,basic,parent_office,pincode,daily_ta_fare,mileage_fare,max_bike,submit_to,submit_every,is_admin) values ('anandnkl@gmail.com','ANAND M','SYSTEM MANAGER','41600','NAMAKKAL DO','637001',625.0,15.0,500.0,'Superintendent of Postoffices, Namakkal Division','FORTNIGHTLY',false) on conflict (email) do nothing;
insert into ta_profiles(email,name,designation,basic,parent_office,pincode,daily_ta_fare,mileage_fare,max_bike,submit_to,submit_every,is_admin) values ('arulece05@gmail.com','Arul M','DSM, Karur DO','42800','Karur DO','639001',625.0,15.0,200.0,'The SPO''s,Karur Division,Karur 639001.','FORTNIGHTLY',true) on conflict (email) do nothing;
insert into ta_profiles(email,name,designation,basic,parent_office,pincode,daily_ta_fare,mileage_fare,max_bike,submit_to,submit_every,is_admin) values ('chandrasekaran2143@gmail.com','Chandrasekaran A','MO1, Karur Sub Division','33300','Karur','639001',625.0,12.0,300.0,'The SPO''s,Karur Division,Karur 639001.','WEELKLY',false) on conflict (email) do nothing;
insert into ta_profiles(email,name,designation,basic,parent_office,pincode,daily_ta_fare,mileage_fare,max_bike,submit_to,submit_every,is_admin) values ('deepak.kledsm@gmail.com','Deepak S','DSM, Karur HO','42800','Karur H.O','639001',625.0,15.0,200.0,'The SPO''s,Karur Division,Karur 639001.','FORTNIGHTLY',false) on conflict (email) do nothing;
insert into ta_profiles(email,name,designation,basic,parent_office,pincode,daily_ta_fare,mileage_fare,max_bike,submit_to,submit_every,is_admin) values ('kavinkavin1593@gmail.com','Kavin Kumar C','Jeep Driver','21100','Karur DO','639001',625.0,15.0,500.0,'Supdt of Post Offices','Quarterly',false) on conflict (email) do nothing;
insert into ta_profiles(email,name,designation,basic,parent_office,pincode,daily_ta_fare,mileage_fare,max_bike,submit_to,submit_every,is_admin) values ('kavinkavinkumar925@gmail.com','Kavin Kumar C','Staff Driver, Karur Division, KARUR','20500','Karur DO','639001',625.0,15.0,1000.0,'The SPO''s,Karur Division,Karur 639001.','FORTNIGHTLY',false) on conflict (email) do nothing;
insert into ta_profiles(email,name,designation,basic,parent_office,pincode,daily_ta_fare,mileage_fare,max_bike,submit_to,submit_every,is_admin) values ('lishaleela@gmail.com','TAMILINI A R','SPO''s, Karur Division','74300','Karur','639001',1125.0,15.0,500.0,'The SPO''s,Karur Division,Karur 639001.','FORTNIGHTLY',false) on conflict (email) do nothing;
insert into ta_profiles(email,name,designation,basic,parent_office,pincode,daily_ta_fare,mileage_fare,max_bike,submit_to,submit_every,is_admin) values ('mail2rekhu@gmail.com','N. Revathy','Inspector Posts, Aravakurichi sub division','50500+DA','Pallapatti','639205',1000.0,15.0,200.0,'The SPOs, Karur Division, Karur','FORTNIGHTLY',false) on conflict (email) do nothing;
insert into ta_profiles(email,name,designation,basic,parent_office,pincode,daily_ta_fare,mileage_fare,max_bike,submit_to,submit_every,is_admin) values ('ramani625@gmail.com','Ramani625','','','','',0.0,0.0,0.0,'','Fortnight',false) on conflict (email) do nothing;
insert into ta_profiles(email,name,designation,basic,parent_office,pincode,daily_ta_fare,mileage_fare,max_bike,submit_to,submit_every,is_admin) values ('sa637211@gmail.com','P Suresh','System Manager, Namakkal HO','41400','Namakkal HO','637001',625.0,15.0,200.0,'The SPO''s,Namakkal Division,Namakkal 637001.','FORTNIGHTLY',false) on conflict (email) do nothing;
insert into ta_profiles(email,name,designation,basic,parent_office,pincode,daily_ta_fare,mileage_fare,max_bike,submit_to,submit_every,is_admin) values ('sarav.bpm@gmail.com','SARAVANAN S','Mail Overseer II','24500','Karur','639001',625.0,15.0,200.0,'ASP Karur Sub Division','Fortnightly',false) on conflict (email) do nothing;
insert into ta_profiles(email,name,designation,basic,parent_office,pincode,daily_ta_fare,mileage_fare,max_bike,submit_to,submit_every,is_admin) values ('selvaganesanip@gmail.com','P.Selvaganesan','Inspector Posts, Kallakurichi East SD','46200','KALLAKURICHI','606202',1000.0,15.0,500.0,'The SPO''s,Karur Division,Karur 639001.','FORTNIGHTLY',false) on conflict (email) do nothing;
insert into ta_profiles(email,name,designation,basic,parent_office,pincode,daily_ta_fare,mileage_fare,max_bike,submit_to,submit_every,is_admin) values ('smanoj.ece@gmail.com','Manoj S','IP(CS), Karur Division','52000+TA','Karur','639001',1000.0,15.0,500.0,'The SPO''s,Karur Division,Karur 639001.','FORTNIGHTLY',false) on conflict (email) do nothing;
insert into ta_profiles(email,name,designation,basic,parent_office,pincode,daily_ta_fare,mileage_fare,max_bike,submit_to,submit_every,is_admin) values ('sukumaransumathi.ss@gmail.com','Sukumaran R','MO I, Aravakurichi Sub Dn','42800','Aravakurichi Sub Division','639205',625.0,15.0,500.0,'The SPO''s,Karur Division,Karur 639001.','WEELKLY',false) on conflict (email) do nothing;
commit;
